# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161107_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhaar',
            name='mobile',
            field=models.BigIntegerField(default=9999999999L),
            preserve_default=False,
        ),
    ]
